### PR TITLE
Updated readme with install instructions for windows.

### PR DESCRIPTION
**Pull request by golyalpha**
I added installation instructions on how to install the package on Windows (python27 32bit). It's still work in progress, attempting to figure out how to make it use another (working) dependency instead of the original.

### CODE REVIEW

**Comment by golyalpha** [comment]
Instructions finished. Check commit #bf025b7 for more details.

**Comment by pipermerriam** [comment]
I appreciate the work you've done on this, but I'm not entirely comfortable directing people towards external executables in the README of this project.  I appreciate your exploration into this issue and I expect it will be helpful to others who run into the same issue.

**Comment by golyalpha** [comment]
Well, they are all open source, so that shouldn't be an issue. I can change that though if you really want to.

**Comment by golyalpha** [comment]
I also updated the linux instalation instructions, in order for it to work on clean linux instalations (currently Ubuntu/Debian-only).

**Comment by pipermerriam** [comment]
👍 is there any additional work you plan to do on this?  Let me know when you are *done* and I'll get this merged.

**Comment by golyalpha** [comment]
If I'll do some more work on this, I will just start a new pull request, but I don't think I'll find anything to work on here for now. Plus, it would most probably be off-topic on this pull request, so yeah, I'm done for now. Merge it.

**Comment by pipermerriam** [comment]
Thank you very much for your contribution.

**Pull request merged**
